-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE hrms."User"
(
    "Id" integer NOT NULL,
    email character varying(50) NOT NULL,
    password character(20) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE hrms."Employer"
(
    employer_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_site character varying(50) NOT NULL,
    telephone character(12) NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE hrms."Candidate"
(
    candidate_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    tc_no character(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (candidate_id)
);

CREATE TABLE hrms."Admin"
(
    admin_id integer NOT NULL,
    first_name character varying(25)[] NOT NULL,
    last_name character varying(25)[] NOT NULL,
    PRIMARY KEY (admin_id)
);

CREATE TABLE hrms."Job"
(
    job_id integer NOT NULL,
    title character varying(50) NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (job_id)
);

CREATE TABLE hrms.activation_code
(
    "Id" integer NOT NULL,
    activation_code "char",
    sent_date "char",
    expire_date "char",
    confirmation_date "char",
    is_confirmed boolean NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE hrms.employer_activation
(
    activation_code_id integer NOT NULL,
    employer_id integer NOT NULL,
    admin_id integer NOT NULL,
    PRIMARY KEY (activation_code_id)
);

CREATE TABLE hrms.candidate_activation
(
    activation_code_id integer NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (activation_code_id)
);

ALTER TABLE hrms."Candidate"
    ADD FOREIGN KEY (candidate_id)
    REFERENCES hrms."User" ("Id")
    NOT VALID;


ALTER TABLE hrms."Admin"
    ADD FOREIGN KEY (admin_id)
    REFERENCES hrms."User" ("Id")
    NOT VALID;


ALTER TABLE hrms."Employer"
    ADD FOREIGN KEY (employer_id)
    REFERENCES hrms."User" ("Id")
    NOT VALID;


ALTER TABLE hrms.activation_code
    ADD FOREIGN KEY (activation_code)
    REFERENCES hrms.employer_activation (activation_code_id)
    NOT VALID;


ALTER TABLE hrms.activation_code
    ADD FOREIGN KEY ("Id")
    REFERENCES hrms.candidate_activation (activation_code_id)
    NOT VALID;


ALTER TABLE hrms.employer_activation
    ADD FOREIGN KEY (activation_code_id)
    REFERENCES hrms."Admin" (admin_id)
    NOT VALID;


ALTER TABLE hrms."Job"
    ADD FOREIGN KEY (employer_id)
    REFERENCES hrms."Employer" (employer_id)
    NOT VALID;

END;
